### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by netgh72** [budulinek/Daikin-P1P2---UDP-Gateway#13]
Hi, thanx for your great work,
i tried to use this but i always get:

Compilation error: 'jsonVal' was not declared in this scope

any ideas?
Thanx!

Gerd

**Comment by budulinek** [comment]
Can not reproduce. Did you download all files? You need all INOs to compile.

'jsonVal' is declared in 05-pages.ino

**Comment by netgh72** [comment]
Hi, 
i think i can flash now the arduino,
i think my problem ist the ethernet connection,
my ip range is not 192.168.1.xxx and every change i make can't solve the problem.

after flash i can ping 192.168.1.254,
when i change the advanced settings.h to my range theres no effect after flash,
no ping to my settings, but to 192.168.1.254!

my knowledge of programming is little poor so i dont know what to do,
maybe you can help a little bit?

Thanx, Gerd

**Comment by netgh72** [comment]
Update:

Sorry, then ping form 192.168.1.254 ok comes too when the board/shield is not connected, it commes from my router!?!

**Comment by budulinek** [comment]
If you receive ping when the board/shield is not connected to the network, it means you have other device with (static) IP 192.168.1.254. That "other device" could be the router itself.
