### ISSUE TITLE
Will this work for a Daikin ducted air condition unit ?

### ISSUE THREAD

**Issue by yiannosi** [budulinek/Daikin-P1P2---UDP-Gateway#17]
Does anyone know if this project would work on a Daikin Ducted AC unit with wired controller on P1P2 interface ?
If yes, I would be interested to use basic libraries  to built an arduino based controller on ESP8266/ESP32 chip.

**Comment by budulinek** [comment]
No, this project works only on Daikin Altherma heat pumps.
